name: bundlesize
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  bundlesize:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@graphcommerce'
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          path: old
          ref: ${{ github.base_ref }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          working-directory: new
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn --cwd ./new/examples/magento-graphcms build > new.txt
      - run: cat new.txt
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          working-directory: old
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn --cwd ./old/examples/magento-graphcms build > old.txt
      - run: cat old.txt
      - uses: ho-nl/next-bundlesize-action@master
        id: 'bundlesize'
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.bundlesize.outputs.diff != ''
        with:
          msg: ${{steps.bundlesize.outputs.diff}}
          check_for_duplicate_msg: false
